### ISSUE TITLE
I am having the issue of "list index out of range" help 😥

### ISSUE THREAD

**Issue by shreesha345** [CleoMenezes/WhatsApp-ChatBot#1]
`Traceback (most recent call last):
  File ".\main.py", line 78, in <module>
    run.chat_bot()
  File ".\main.py", line 55, in chat_bot
    text_msg = self.get_msg()
  File ".\main.py", line 36, in get_msg
    text_msg = msg[self.last_massage].find_elment_by_class_name("_ccCW FqYAR i0jNr")
IndexError: list index out of range`

when I run this first It asks me the name of my friend whom I want to use this bot in WhatsApp 
and then it will open the page where I should scan the QRcode and then I pressed enter in my cmd and then 
when my friend sends a message it gives me this error 😥😥😥😥😥
Please help me please fast as possible 
Thank you!

**Comment by CleoMenezesJr** [comment]
This happens because whatsapp periodically changes the class name of the elements. You can implement this manually or wait until the weekend.
